### ISSUE TITLE
Playlist not showing all the song in a playlist

### ISSUE THREAD

**Issue by EONTWINE** [Alaanor/beatlist#70] opened 2020-11-19 21:06 UTC
A few of the playlists i have downloaded does not show all the songs.

The "Anniversary Song Pack" only show 25 songs, but there are 44 songs when looking at bsaber.
The "Maps for New Players" only shows 73 songs, but there are 102 songs.

There are multiple playlist with this issue.

**Comment by Alaanor** [comment] 2020-11-19 21:41
I just tried on my side, indeed. It's not a bug tho. It's just beatsaver server being slow to response (overloaded I guess) and they timeout on beatlist. (We waited for their answered but they don't answer, so we drop out the download and try another).

Quick and dirty solution is to go on the playlist and attempt again to download the missing out (select all and click on download, it will only download the missing ones). After some iterations you should get all of them. I tried with the anniversary pack and got almost of them after 2-3 iterations.

To be honest, idk if I can make any proper solution to this. I could do some mechanism to automatically attempt 2-3 time later again. But I think beatsaver server have enough traffics like this, it is not in my wish to promote request spamming. I'll prefer to keep this behavior of "re-attempt to download" manual.

I'll close the issue for now but if you get any good idea to share, I'd be glad to listen.

**Closed by Alaanor** 2020-11-19 21:41 UTC
