### ISSUE TITLE
forbidden symbol in song title causes error

### ISSUE THREAD

**Issue by HightechFairy** [Alaanor/beatlist#37] opened 2020-04-24 19:04 UTC
When a song has a symbol in the title that Windows doesn't allow in a folder name you get an error that the folder couldn't be created without any description of why it failed. Could beatlist be reworked to notice these symbols and drop them from the folder name when downloading new songs?
It happened to me with this song that has the * symbol in its name:
https://bsaber.com/songs/9e27/

**Comment by Alaanor** [comment] 2020-04-24 19:11
duplicate of #20 and #35. TLDR; 1.2 will fix it and the code is already done on this point 😄

**Closed by Alaanor** 2020-04-24 19:11 UTC
