### ISSUE TITLE
Put the "Preview Beatmap" button on the Song Browser screen

### ISSUE THREAD

**Issue by Gordin** [Alaanor/beatlist#45] opened 2020-06-01 11:13 UTC
Just a suggestion, but having the preview button on the browser screen would make it much easier to just open a lot of browser tabs of song previews and then download the maps you like. The download button in the browser view is kinda pointless without the preview button (at least for me) because I never download a song without looking at the preview anyway.

**Comment by Alaanor** [comment] 2020-06-01 11:21
Duplicate of #42, fixed with #43 This will be on the next release 👌

**Closed by Alaanor** 2020-06-01 11:21 UTC
