### ISSUE TITLE
Beatlist unresponsive after using sort filters in browser playlists

### ISSUE THREAD

**Issue by ANewDawn** [Alaanor/beatlist#46] opened 2020-06-02 19:14 UTC
When you click on any of the sort arrow on song name, artist etc in the browser section of playlists, the program becomes unresponsive after.

**Comment by Alaanor** [comment] 2020-06-02 19:21
Do you happens to have a lot of beatmap (if so, how many, just trying to gauge) ? or maybe you're displaying all instead of a limited number ?

What I'm trying to find out first is the fact it's a bug or a performance issue.

**Comment by ANewDawn** [comment] 2020-06-02 19:23
@Alaanor only 35 songs so not a lot

**Comment by Alaanor** [comment] 2020-06-02 19:35
Mhhh, I can't reproduce. 35 songs should be, indeed, blazing fast.

Maybe you have a playlist that has a songs/mapper/any fields with weird character and some strange behavior happens on this ? Can you confirm this happens with all yours playlists **and** in beatmap local too ?

**Comment by ANewDawn** [comment] 2020-06-02 19:48
Solved it. Apparently had few duplicate songs in the beatmap local list for some reason. Removed them and cleared cache. 

Working ok now 👍

**Comment by Alaanor** [comment] 2020-06-02 19:52
Oh nice. That would still be a bug that exists, I tried to duplicate a song on my side and check if this indeed crash. It does not 😦. Since I cannot reproduce and you solved the issue. I'm going to close this 👌 .

**Closed by Alaanor** 2020-06-02 19:52 UTC
