### ISSUE TITLE
Online playlist view lacks of items witch appears on the website.

### ISSUE THREAD

**Issue by nargatte** [Alaanor/beatlist#64] opened 2020-08-26 19:48 UTC
I point playlist pack that do not appear in the program.
![image](https://user-images.githubusercontent.com/13699879/91349124-21ded480-e7e5-11ea-88de-d651cd64e238.png)
![image](https://user-images.githubusercontent.com/13699879/91349241-52bf0980-e7e5-11ea-829c-8cdd2e118ab3.png)
![image](https://user-images.githubusercontent.com/13699879/91349465-9c0f5900-e7e5-11ea-9751-b6682ee8fff4.png)
![image](https://user-images.githubusercontent.com/13699879/91349556-be08db80-e7e5-11ea-97ee-53890caed536.png)

**Comment by Alaanor** [comment] 2020-08-26 20:01
I think it's because the endpoint exposed by beastsaber is manually updated iirc.

https://github.com/Alaanor/beatlist/blob/b60464eca29490455baefd94925ef5bc2c2d6224/src/libraries/net/bsaber/BeastsaberAPI.ts#L8-L9

> https://bsaber.com/PlaylistAPI/playlistAPI.json

Here's the url used to fetch the content. So unless beastsaber (or bsaber shortly) have a new endpoint on which I can fetch more content, I don't think I can do much unfortunately. 😞

**Comment by Alaanor** [comment] 2020-08-26 20:11
This is a valid issue, so I will let the thread open for a few days/months in case we find a better solution.

**Comment by Alaanor** [comment] 2020-08-27 15:58
It has been confirmed on their discord server that they need to update on their side to update things. It is something I cannot fix myself. Closing the issue as wont-fix.

**Closed by Alaanor** 2020-08-27 15:58 UTC
Labels: wontfix

**Comment by Alaanor** [comment] 2020-09-01 17:26
@nargatte joestatic updated the json, you should now have the playlist displayed in beatlist 👍 Thanks to him
