### ISSUE TITLE
Json isn't deserialized properly

### ISSUE THREAD

**Issue by sentientyeet** [Alaanor/beatlist#56] opened 2020-07-10 12:32 UTC
Any playlist that has uppercase as the first letter will not be read, won't even show up in the playlists.
For example, playlistTitle works, but PlaylistTitle doesn't. Same goes for image, description, song hash etc.

**Comment by SpellcheckerExtraordinaire** [comment] 2020-08-21 00:06
Not affiliated with this project, but  tried to reproduce this, but it seems uppercase letters work fine. Do you literally mean that you changed the "playlistTitle" part? That is the key, not the value and that would indeed not work.

**Comment by sentientyeet** [comment] 2020-08-24 12:04
Yeah I mean the case sensitivity. It seems like BMBF processes things like this correctly though.

**Comment by Alaanor** [comment] 2020-08-24 12:14
I finally understood what you meant by playlistTitle. As @SpellcheckerExtraordinaire said, the json key of that property should be case sensitive under normal condition. That's how it should be. Now it is possible to make it case insensitive but it's extra work to add inconsistency and I judge it to be unnecessary.

I'm more interested to know from where you got this PlaylistTitle with a uppercase P. Because if it's just one tool that generate it like this, I'm tempted to instead tell that author to change (or PR if open source). If it's multiple tools that use that uppercase P, I'd better make it more flexible here.

There's no proper definition for this playlist format, I had to look at how others were generating it.

**Comment by sentientyeet** [comment] 2020-08-29 19:38
> I'm more interested to know from where you got this PlaylistTitle with a uppercase P. Because if it's just one tool that generate it like this, I'm tempted to instead tell that author to change (or PR if open source). If it's multiple tools that use that uppercase P, I'd better make it more flexible here.
There was this guy on bsaber that wrote a crawler for ranked maps and that's how I found it.

**Comment by Alaanor** [comment] 2020-08-29 19:49
I checked how this plugin was loading the key. Judging quickly from the code, it doesn't seems it would load with the right title if beatlist was less restrictive.

https://github.com/rithik-b/PlaylistLoaderPlugin/blob/cf90997a158e2160134e5a4a2170ac37ffeaff98/PlaylistLoaderPlugin/LoadPlaylistScript.cs#L52

For now I will close the issue as wont-fix. I prefer keeping beatlist strict so once it load on beatlist, you can be confident it would load in the game as well.

As reminder there's this panel available in beatlist, a bit hidden but it is here. 
![image](https://user-images.githubusercontent.com/8039130/91644973-68c90600-ea41-11ea-9790-d66fe6c0b5bd.png)
![image](https://user-images.githubusercontent.com/8039130/91644976-6d8dba00-ea41-11ea-8027-2ad72870a6b6.png)

**Closed by Alaanor** 2020-08-29 19:49 UTC
